{{- if or .Values.vantaToken .Values.drataKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "plexar.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "plexar.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.vantaToken }}
  vanta-token: {{ .Values.vantaToken | quote }}
  {{- end }}
  {{- if .Values.drataKey }}
  drata-key: {{ .Values.drataKey | quote }}
  {{- end }}
{{- end }}
